services: 
  csp:
    image: harpocrates/distributed_hhe_ppml
    build:
      context: .
      network: host
    entrypoint: csp
    command: ${CSP_HOST}:${CSP_PORT}
    tty: true 
    network_mode: "host"
    ports:
      - ${CSP_PORT}:${CSP_PORT}
    expose:
      - ${CSP_PORT}
    volumes:
      - ${CSP_WORKDIR}:/srv
    environment:
      - CSP_HOST=${CSP_HOST}
      - CSP_PORT=${CSP_PORT}

  analyst:
    image: harpocrates/distributed_hhe_ppml
    build:
      context: .
      network: host
    entrypoint: analyst
    command: ${ANALYST_HOST}:${ANALYST_PORT} ${CSP_HOST}:${CSP_PORT}
    tty: true 
    network_mode: "host"
    ports:
      - ${ANALYST_PORT}:${ANALYST_PORT}
    expose:
      - ${ANALYST_PORT}
    volumes:
      - ${ANALYST_WORKDIR}:/srv 
    environment:
      - ANALYST_HOST=${ANALYST_HOST}
      - ANALYST_PORT=${ANALYST_PORT}
      - CSP_HOST=${CSP_HOST}
      - CSP_PORT=${CSP_PORT}
