// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hhe.proto

#include "hhe.pb.h"
#include "hhe.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hheproto {

static const char* AnalystService_method_names[] = {
  "/hheproto.AnalystService/getPublicKey",
  "/hheproto.AnalystService/addEncryptedResult",
};

std::unique_ptr< AnalystService::Stub> AnalystService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AnalystService::Stub> stub(new AnalystService::Stub(channel, options));
  return stub;
}

AnalystService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getPublicKey_(AnalystService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_addEncryptedResult_(AnalystService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AnalystService::Stub::getPublicKey(::grpc::ClientContext* context, const ::hheproto::Empty& request, ::hheproto::PublicKeyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::Empty, ::hheproto::PublicKeyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getPublicKey_, context, request, response);
}

void AnalystService::Stub::async::getPublicKey(::grpc::ClientContext* context, const ::hheproto::Empty* request, ::hheproto::PublicKeyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::Empty, ::hheproto::PublicKeyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getPublicKey_, context, request, response, std::move(f));
}

void AnalystService::Stub::async::getPublicKey(::grpc::ClientContext* context, const ::hheproto::Empty* request, ::hheproto::PublicKeyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getPublicKey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::PublicKeyMsg>* AnalystService::Stub::PrepareAsyncgetPublicKeyRaw(::grpc::ClientContext* context, const ::hheproto::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::PublicKeyMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getPublicKey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::PublicKeyMsg>* AnalystService::Stub::AsyncgetPublicKeyRaw(::grpc::ClientContext* context, const ::hheproto::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetPublicKeyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AnalystService::Stub::addEncryptedResult(::grpc::ClientContext* context, const ::hheproto::CiphertextResult& request, ::hheproto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::CiphertextResult, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addEncryptedResult_, context, request, response);
}

void AnalystService::Stub::async::addEncryptedResult(::grpc::ClientContext* context, const ::hheproto::CiphertextResult* request, ::hheproto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::CiphertextResult, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedResult_, context, request, response, std::move(f));
}

void AnalystService::Stub::async::addEncryptedResult(::grpc::ClientContext* context, const ::hheproto::CiphertextResult* request, ::hheproto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* AnalystService::Stub::PrepareAsyncaddEncryptedResultRaw(::grpc::ClientContext* context, const ::hheproto::CiphertextResult& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::Empty, ::hheproto::CiphertextResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addEncryptedResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* AnalystService::Stub::AsyncaddEncryptedResultRaw(::grpc::ClientContext* context, const ::hheproto::CiphertextResult& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddEncryptedResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

AnalystService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalystService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalystService::Service, ::hheproto::Empty, ::hheproto::PublicKeyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalystService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::Empty* req,
             ::hheproto::PublicKeyMsg* resp) {
               return service->getPublicKey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalystService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalystService::Service, ::hheproto::CiphertextResult, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalystService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::CiphertextResult* req,
             ::hheproto::Empty* resp) {
               return service->addEncryptedResult(ctx, req, resp);
             }, this)));
}

AnalystService::Service::~Service() {
}

::grpc::Status AnalystService::Service::getPublicKey(::grpc::ServerContext* context, const ::hheproto::Empty* request, ::hheproto::PublicKeyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AnalystService::Service::addEncryptedResult(::grpc::ServerContext* context, const ::hheproto::CiphertextResult* request, ::hheproto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* CSPService_method_names[] = {
  "/hheproto.CSPService/addPublicKeys",
  "/hheproto.CSPService/addEncryptedKeys",
  "/hheproto.CSPService/addEncryptedData",
  "/hheproto.CSPService/addMLModel",
  "/hheproto.CSPService/evaluateModel",
};

std::unique_ptr< CSPService::Stub> CSPService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CSPService::Stub> stub(new CSPService::Stub(channel, options));
  return stub;
}

CSPService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_addPublicKeys_(CSPService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_addEncryptedKeys_(CSPService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_addEncryptedData_(CSPService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_addMLModel_(CSPService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_evaluateModel_(CSPService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CSPService::Stub::addPublicKeys(::grpc::ClientContext* context, const ::hheproto::PublicKeySetMsg& request, ::hheproto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::PublicKeySetMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addPublicKeys_, context, request, response);
}

void CSPService::Stub::async::addPublicKeys(::grpc::ClientContext* context, const ::hheproto::PublicKeySetMsg* request, ::hheproto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::PublicKeySetMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addPublicKeys_, context, request, response, std::move(f));
}

void CSPService::Stub::async::addPublicKeys(::grpc::ClientContext* context, const ::hheproto::PublicKeySetMsg* request, ::hheproto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addPublicKeys_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::PrepareAsyncaddPublicKeysRaw(::grpc::ClientContext* context, const ::hheproto::PublicKeySetMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::Empty, ::hheproto::PublicKeySetMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addPublicKeys_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::AsyncaddPublicKeysRaw(::grpc::ClientContext* context, const ::hheproto::PublicKeySetMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddPublicKeysRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CSPService::Stub::addEncryptedKeys(::grpc::ClientContext* context, const ::hheproto::EncSymmetricKeysMsg& request, ::hheproto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::EncSymmetricKeysMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addEncryptedKeys_, context, request, response);
}

void CSPService::Stub::async::addEncryptedKeys(::grpc::ClientContext* context, const ::hheproto::EncSymmetricKeysMsg* request, ::hheproto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::EncSymmetricKeysMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedKeys_, context, request, response, std::move(f));
}

void CSPService::Stub::async::addEncryptedKeys(::grpc::ClientContext* context, const ::hheproto::EncSymmetricKeysMsg* request, ::hheproto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedKeys_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::PrepareAsyncaddEncryptedKeysRaw(::grpc::ClientContext* context, const ::hheproto::EncSymmetricKeysMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::Empty, ::hheproto::EncSymmetricKeysMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addEncryptedKeys_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::AsyncaddEncryptedKeysRaw(::grpc::ClientContext* context, const ::hheproto::EncSymmetricKeysMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddEncryptedKeysRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CSPService::Stub::addEncryptedData(::grpc::ClientContext* context, const ::hheproto::EncSymmetricDataMsg& request, ::hheproto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::EncSymmetricDataMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addEncryptedData_, context, request, response);
}

void CSPService::Stub::async::addEncryptedData(::grpc::ClientContext* context, const ::hheproto::EncSymmetricDataMsg* request, ::hheproto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::EncSymmetricDataMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedData_, context, request, response, std::move(f));
}

void CSPService::Stub::async::addEncryptedData(::grpc::ClientContext* context, const ::hheproto::EncSymmetricDataMsg* request, ::hheproto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::PrepareAsyncaddEncryptedDataRaw(::grpc::ClientContext* context, const ::hheproto::EncSymmetricDataMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::Empty, ::hheproto::EncSymmetricDataMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addEncryptedData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::AsyncaddEncryptedDataRaw(::grpc::ClientContext* context, const ::hheproto::EncSymmetricDataMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddEncryptedDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CSPService::Stub::addMLModel(::grpc::ClientContext* context, const ::hheproto::MLModelMsg& request, ::hheproto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::MLModelMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addMLModel_, context, request, response);
}

void CSPService::Stub::async::addMLModel(::grpc::ClientContext* context, const ::hheproto::MLModelMsg* request, ::hheproto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::MLModelMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addMLModel_, context, request, response, std::move(f));
}

void CSPService::Stub::async::addMLModel(::grpc::ClientContext* context, const ::hheproto::MLModelMsg* request, ::hheproto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addMLModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::PrepareAsyncaddMLModelRaw(::grpc::ClientContext* context, const ::hheproto::MLModelMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::Empty, ::hheproto::MLModelMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addMLModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::AsyncaddMLModelRaw(::grpc::ClientContext* context, const ::hheproto::MLModelMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddMLModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CSPService::Stub::evaluateModel(::grpc::ClientContext* context, const ::hheproto::CiphertextBytes& request, ::hheproto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::CiphertextBytes, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_evaluateModel_, context, request, response);
}

void CSPService::Stub::async::evaluateModel(::grpc::ClientContext* context, const ::hheproto::CiphertextBytes* request, ::hheproto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::CiphertextBytes, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_evaluateModel_, context, request, response, std::move(f));
}

void CSPService::Stub::async::evaluateModel(::grpc::ClientContext* context, const ::hheproto::CiphertextBytes* request, ::hheproto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_evaluateModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::PrepareAsyncevaluateModelRaw(::grpc::ClientContext* context, const ::hheproto::CiphertextBytes& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::Empty, ::hheproto::CiphertextBytes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_evaluateModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* CSPService::Stub::AsyncevaluateModelRaw(::grpc::ClientContext* context, const ::hheproto::CiphertextBytes& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncevaluateModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

CSPService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CSPService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CSPService::Service, ::hheproto::PublicKeySetMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CSPService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::PublicKeySetMsg* req,
             ::hheproto::Empty* resp) {
               return service->addPublicKeys(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CSPService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CSPService::Service, ::hheproto::EncSymmetricKeysMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CSPService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::EncSymmetricKeysMsg* req,
             ::hheproto::Empty* resp) {
               return service->addEncryptedKeys(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CSPService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CSPService::Service, ::hheproto::EncSymmetricDataMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CSPService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::EncSymmetricDataMsg* req,
             ::hheproto::Empty* resp) {
               return service->addEncryptedData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CSPService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CSPService::Service, ::hheproto::MLModelMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CSPService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::MLModelMsg* req,
             ::hheproto::Empty* resp) {
               return service->addMLModel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CSPService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CSPService::Service, ::hheproto::CiphertextBytes, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CSPService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::CiphertextBytes* req,
             ::hheproto::Empty* resp) {
               return service->evaluateModel(ctx, req, resp);
             }, this)));
}

CSPService::Service::~Service() {
}

::grpc::Status CSPService::Service::addPublicKeys(::grpc::ServerContext* context, const ::hheproto::PublicKeySetMsg* request, ::hheproto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CSPService::Service::addEncryptedKeys(::grpc::ServerContext* context, const ::hheproto::EncSymmetricKeysMsg* request, ::hheproto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CSPService::Service::addEncryptedData(::grpc::ServerContext* context, const ::hheproto::EncSymmetricDataMsg* request, ::hheproto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CSPService::Service::addMLModel(::grpc::ServerContext* context, const ::hheproto::MLModelMsg* request, ::hheproto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CSPService::Service::evaluateModel(::grpc::ServerContext* context, const ::hheproto::CiphertextBytes* request, ::hheproto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hheproto

