// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hhe.proto

#include "hhe.pb.h"
#include "hhe.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hheproto {

static const char* AnalystService_method_names[] = {
  "/hheproto.AnalystService/getPublicKey",
  "/hheproto.AnalystService/addEncryptedResult",
};

std::unique_ptr< AnalystService::Stub> AnalystService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AnalystService::Stub> stub(new AnalystService::Stub(channel, options));
  return stub;
}

AnalystService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getPublicKey_(AnalystService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_addEncryptedResult_(AnalystService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AnalystService::Stub::getPublicKey(::grpc::ClientContext* context, const ::hheproto::Empty& request, ::hheproto::PublicKeyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::Empty, ::hheproto::PublicKeyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getPublicKey_, context, request, response);
}

void AnalystService::Stub::async::getPublicKey(::grpc::ClientContext* context, const ::hheproto::Empty* request, ::hheproto::PublicKeyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::Empty, ::hheproto::PublicKeyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getPublicKey_, context, request, response, std::move(f));
}

void AnalystService::Stub::async::getPublicKey(::grpc::ClientContext* context, const ::hheproto::Empty* request, ::hheproto::PublicKeyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getPublicKey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::PublicKeyMsg>* AnalystService::Stub::PrepareAsyncgetPublicKeyRaw(::grpc::ClientContext* context, const ::hheproto::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::PublicKeyMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getPublicKey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::PublicKeyMsg>* AnalystService::Stub::AsyncgetPublicKeyRaw(::grpc::ClientContext* context, const ::hheproto::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetPublicKeyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AnalystService::Stub::addEncryptedResult(::grpc::ClientContext* context, const ::hheproto::CiphertextMsg& request, ::hheproto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hheproto::CiphertextMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addEncryptedResult_, context, request, response);
}

void AnalystService::Stub::async::addEncryptedResult(::grpc::ClientContext* context, const ::hheproto::CiphertextMsg* request, ::hheproto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hheproto::CiphertextMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedResult_, context, request, response, std::move(f));
}

void AnalystService::Stub::async::addEncryptedResult(::grpc::ClientContext* context, const ::hheproto::CiphertextMsg* request, ::hheproto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addEncryptedResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* AnalystService::Stub::PrepareAsyncaddEncryptedResultRaw(::grpc::ClientContext* context, const ::hheproto::CiphertextMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hheproto::Empty, ::hheproto::CiphertextMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addEncryptedResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hheproto::Empty>* AnalystService::Stub::AsyncaddEncryptedResultRaw(::grpc::ClientContext* context, const ::hheproto::CiphertextMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddEncryptedResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

AnalystService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalystService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalystService::Service, ::hheproto::Empty, ::hheproto::PublicKeyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalystService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::Empty* req,
             ::hheproto::PublicKeyMsg* resp) {
               return service->getPublicKey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalystService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalystService::Service, ::hheproto::CiphertextMsg, ::hheproto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalystService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hheproto::CiphertextMsg* req,
             ::hheproto::Empty* resp) {
               return service->addEncryptedResult(ctx, req, resp);
             }, this)));
}

AnalystService::Service::~Service() {
}

::grpc::Status AnalystService::Service::getPublicKey(::grpc::ServerContext* context, const ::hheproto::Empty* request, ::hheproto::PublicKeyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AnalystService::Service::addEncryptedResult(::grpc::ServerContext* context, const ::hheproto::CiphertextMsg* request, ::hheproto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hheproto

